- alias: Turn On/Off Monitor
  trigger:
  - platform: state
    entity_id: switch.monitor
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service: remote.send_command
    data:
      entity_id: remote.mi_ir_controller
      command: power_monitor

- alias: Turn On/Off Monitor When Desktop Is Turned ON/OFF
  trigger:
  - platform: state
    entity_id: binary_sensor.yunhan_desktop
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service_template: switch.turn_{{ trigger.to_state.state }}
    data:
      entity_id: switch.monitor

- alias: Turn On Monitor After Seating
  trigger:
    - platform: state
      entity_id: binary_sensor.desk_chair
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.monitor
      state: 'off'
  action:
    - service_template: switch.turn_on
      data:
        entity_id: switch.monitor

- alias: Turn Off Monitor After Leaving
  trigger:
    - platform: state
      entity_id: binary_sensor.desk_chair
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: switch.monitor
      state: 'on'
  action:
    - service_template: switch.turn_off
      data:
        entity_id: switch.monitor
