##########################################################
# MI Air Purifier
##########################################################
- alias: mqtt_mi_air_purifier_st
  trigger:
  - platform: mqtt
    topic: smartthings/Mi Air Purifier/switch
  condition:
  - condition: template
    value_template: "{{ states('binary_sensor.mi_air_purifier') != states('fan.mi_air_purifier') }}"
  action:
  - data_template:
      entity_id: fan.mi_air_purifier
    service_template:  >
      fan.turn_{{ trigger.payload }}

- alias: mqtt_mi_air_purifier_ha
  trigger:
  - platform: state
    entity_id: fan.mi_air_purifier
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Mi Air Purifier/switch
      payload: >
        {% if is_state('fan.mi_air_purifier', 'on') %}on{% else %}off{% endif %}


##########################################################
# MI Stading Fan
##########################################################
- alias: mqtt_mi_standing_fan_st
  trigger:
  - platform: mqtt
    topic: smartthings/Mi Standing Fan/switch
  condition:
  - condition: template
    value_template: "{{ states('binary_sensor.mi_standing_fan') != states('fan.mi_standing_fan') }}"
  action:
  - data_template:
      entity_id: fan.mi_standing_fan
    service_template:  >
      fan.turn_{{ trigger.payload }}

- alias: mqtt_mi_standing_fan_ha
  trigger:
  - platform: state
    entity_id: fan.mi_standing_fan
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Mi Standing Fan/switch
      payload: >
        {% if is_state('fan.mi_standing_fan', 'on') %}on{% else %}off{% endif %}

##########################################################
# Samsung Air Conditioner
##########################################################
- alias: mqtt_samsung_air_conditioner_st
  trigger:
  - platform: mqtt
    topic: smartthings/Samsung Air Conditioner/switch
  condition: []
  action:
  - service_template: >
      script.script_turn_{% if is_state('switch.samsung_air_conditioner', 'on') %}on{% else %}off{% endif %}_my_room_ac

##########################################################
# Passage Light
##########################################################
- alias: mqtt_passage_light_ha
  trigger:
  - platform: state
    entity_id: switch.passage_light_switchbot
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Passage Light/switch
      payload: >
        {% if is_state('switch.passage_light_switchbot', 'on') %}on{% else %}off{% endif %}


##########################################################
# Heating Control
##########################################################
- alias: mqtt_heating_control_ha
  trigger:
  - platform: state
    entity_id: switch.heating_control_switchbot
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Heating Control/switch
      payload: >
        {% if is_state('switch.heating_control_switchbot', 'on') %}on{% else %}off{% endif %}
