- alias: Notify Entrance door's change
  trigger:
  - platform: state
    entity_id: binary_sensor.entrance_door
  condition: []
  action:
  - service: notify.me
    data_template:
      title: 'Notify'
      message: "{% if trigger.to_state.state == 'on' %}🚪문이 열렸습니다{% else %}🚪문이 닫혔습니다{% endif %}"
