##########################################################
# Virtual Presence
##########################################################
- alias: Minjun's Android Presence to ST
  trigger:
  - platform: state
    entity_id: device_tracker.minjun_android
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Minjun's Presence/presence
      payload: >
          {% if trigger.to_state.state == 'home' %}present{% else %}not present{% endif %}

- alias: Hyunjun's Android Presence to ST
  trigger:
  - platform: state
    entity_id: device_tracker.hyunjun_android
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Hyunjun's Presence/presence
      payload: >
          {% if trigger.to_state.state == 'home' %}present{% else %}not present{% endif %}

- alias: Mom's iPhone Presence to ST
  trigger:
  - platform: state
    entity_id: device_tracker.mom_iphone
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Mom's Presence/presence
      payload: >
          {% if trigger.to_state.state == 'home' %}present{% else %}not present{% endif %}

- alias: Granma's Android Presence to ST
  trigger:
  - platform: state
    entity_id: device_tracker.grandma_android
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Grandma's Presence/presence
      payload: >
          {% if trigger.to_state.state == 'home' %}present{% else %}not present{% endif %}

##########################################################
# Yunhan's Presence
##########################################################
- alias: SPBEAR's WiFi to ST
  trigger:
  - platform: state
    entity_id: device_tracker.yunhan_android
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: smartthings/Yunhan's WiFi/presence
        payload: >
          {% if trigger.to_state.state == 'home' %}present{% else %}not present{% endif %}

- alias: Yunhan's HA to ST
  trigger:
  - platform: state
    entity_id: binary_sensor.yunhan_android
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: smartthings/Yunhan's Presence/presence
        payload: >
          {% if trigger.to_state.state == 'home' %}present{% else %}not present{% endif %}

##########################################################
# Desktop
##########################################################
- alias: SPBEAR's Desktop Presence to ST
  trigger:
  - platform: state
    entity_id: device_tracker.spbear_desktop
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: smartthings/Desktop PC/switch
        payload: >
          {% if trigger.to_state.state == 'home' %}present{% else %}not present{% endif %}
        retain: True

- alias: Yunhan's Macbook Presence to ST
  trigger:
  - platform: state
    entity_id: device_tracker.yunhan_macbook
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: smartthings/Yunhan Macbook/switch
        payload: >
          {% if trigger.to_state.state == 'home' %}present{% else %}not present{% endif %}
        retain: True
