# Close cover when sleep sensor is detected
- alias: Close cover when sleep sensor is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
    to: 'on'
  - platform: state
    entity_id: binary_sensor.window_sensor
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: time
    after: '20:00:00'
    before: '05:00:00'
  - condition: state
    entity_id: switch.curtain_auto_control
    state: 'on'
  - condition: state
    entity_id: binary_sensor.room_bed_sleep
    state: 'on'
  - condition: state
    entity_id: binary_sensor.window_sensor
    state: 'off'
  action:
  - service: cover.close_cover
    data:
        entity_id: cover.window_curtain

# Open cover when sleep sensor is cleared
- alias: Open cover when sleep sensor is cleared
  trigger:
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: time
    after: '06:30:00'
    before: '12:00:00'
  - condition: state
    entity_id: switch.curtain_auto_control
    state: 'on'
  action:
  - service: cover.open_cover
    data:
        entity_id: cover.window_curtain

# Open
- alias: cover_open_0730
  trigger:
  - platform: time
    at: '07:30:00'
  condition: []
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.window_curtain
  - service: switch.turn_on
    data:
      entity_id: switch.curtain_auto_control

- alias: cover_close_sun_below_horizon
  trigger:
    platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: binary_sensor.window_sensor
    state: 'off'
  action:
  - service: cover.close_cover
    data:
        entity_id: cover.window_curtain
  - service: switch.turn_on
    data:
      entity_id: switch.curtain_auto_control

- alias: cover_close_sun_above_horizon
  trigger:
    platform: sun
    event: sunrise
    offset: '-01:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.window_sensor
    state: 'off'
  action:
  - service: cover.close_cover
    data:
        entity_id: cover.window_curtain
  - service: switch.turn_on
    data:
      entity_id: switch.curtain_auto_control
