# Close cover when sleep sensor is detected
- alias: Close cover when sleep sensor is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: time
    after: '20:00:00'
    before: '05:00:00'
  action:
  - service: cover.close_cover
    data:
        entity_id: cover.window_curtain

# Open cover when sleep sensor is cleared
- alias: Open cover when sleep sensor is cleared
  trigger:
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: time
    after: '06:30:00'
    before: '12:00:00'
  action:
  - service: cover.open_cover
    data:
        entity_id: cover.window_curtain

# Open
- alias: cover_open_0730
  trigger:
  - platform: time
    at: '07:30:00'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  action:
  - service: cover.open_cover
    data:
        entity_id: cover.window_curtain

- alias: cover_close_sun_below_horizon
  trigger:
    platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'off'
  action:
  - service: cover.close_cover
    data:
        entity_id: cover.window_curtain

- alias: cover_close_sun_above_horizon
  trigger:
    platform: state
    entity_id: sun.sun
    to: 'above_horizon'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'off'
  action:
  - service: cover.open_cover
    data:
        entity_id: cover.window_curtain
