- alias: Sync Airconditioner Control ON
  trigger:
    - platform: numeric_state
      entity_id: sensor.livingroom_airconditioner_power
      above: 30.0
      for:
        seconds: 5
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: switch.livingroom_airconditioner
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.livingroom_airconditioner_power
      above: 30.0
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.livingroom_airconditioner

- alias: Sync Airconditioner Control OFF
  trigger:
    - platform: numeric_state
      entity_id: sensor.livingroom_airconditioner_power
      below: 30.0
      for:
        seconds: 5
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: switch.livingroom_airconditioner
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.livingroom_airconditioner_power
      below: 30.0
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.livingroom_airconditioner

- alias: Airconditioner Control ON
  trigger:
    - platform: state
      entity_id: switch.livingroom_airconditioner
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.livingroom_airconditioner_power
      below: 30.0
  action:
    - service: switch.toggle
      data:
        entity_id: switch.livingroom_airconditioner_control

- alias: Airconditioner Control OFF
  trigger:
    - platform: state
      entity_id: switch.livingroom_airconditioner
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.livingroom_airconditioner_power
      above: 30.0
  action:
    - service: switch.toggle
      data:
        entity_id: switch.livingroom_airconditioner_control

- alias: Notify Airconditioner Status
  trigger:
  - platform: state
    entity_id: switch.livingroom_airconditioner
  condition: []
  action:
  - service: notify.me
    data_template:
      message: "🌬️ 거실 에어콘을 {% if trigger.to_state.state == 'on' %}🟢 켰어요{% else %}🔴 껐어요{% endif %}"
