- alias: Restroom Light ON
  trigger:
    - platform: state
      entity_id: binary_sensor.restroom_door_status
      from: 'off'
      to: 'on'
  condition: []
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.restroom_light
    - service: switch.turn_on
      data:
        entity_id: switch.restroom_fan

- alias: Restroom Fan ON
  trigger:
    - platform: numeric_state
      entity_id: sensor.restroom_humidity
      above: 55.0
  condition: []
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.restroom_fan

- alias: Restroom Light OFF
  trigger:
    - platform: state
      entity_id: switch.restroom_light
      from: 'off'
      to: 'on'
      for:
          minutes: 20
  condition:
    - condition: state
      entity_id: switch.restroom_light
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.restroom_light

- alias: Restroom Fan OFF
  trigger:
    - platform: state
      entity_id: switch.restroom_fan
      from: 'off'
      to: 'on'
      for:
          minutes: 1
    - platform: numeric_state
      entity_id: sensor.restroom_humidity
      below: 55.0
  condition:
    - condition: state
      entity_id: switch.restroom_fan
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.restroom_humidity
      below: 55.0
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.restroom_fan
