- alias: Fan to Bed
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'off'
      to: 'on'
      for:
        minutes: 1
  condition: []
  action:
    - service: script.turn_on
      data:
        entity_id: script.fan_to_bed

- alias: Fan to Sleep
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'off'
      to: 'on'
      for:
        minutes: 60
  condition: []
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.mi_standing_fan

- alias: Fan to Desk
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'on'
      to: 'off'
      for:
        minutes: 1
  condition: []
  action:
    - service: script.turn_on
      data:
        entity_id: script.fan_to_desk
