- alias: Turn on when CO2 is high
  trigger:
    - platform: numeric_state
      entity_id: sensor.awair_co2
      above: 600
      for:
        minutes: 1
    - platform: time_pattern
      minutes: "/10"
    - platform: state
      entity_id: binary_sensor.yunhan_android
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.external_air_control
      state: 'off'
    - condition: state
      entity_id: binary_sensor.yunhan_android
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.awair_co2
      above: 600
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.external_air_control

- alias: Turn off when CO2 is low
  trigger:
    - platform: numeric_state
      entity_id: sensor.awair_co2
      below: 600
      for:
        minutes: 10
    - platform: time_pattern
      minutes: "/10"
    - platform: state
      entity_id: binary_sensor.yunhan_android
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.external_air_control
      state: 'on'
    - condition: state
      entity_id: binary_sensor.yunhan_android
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.awair_co2
      below: 600
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.external_air_control
