- alias: Turn On Mosquitto Protector
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.hyunjun_android
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.hyunjun_mosquitto_protector

- alias: Turn Off Mosquitto Protector
  trigger:
    - platform: time
      at: '08:00:00'
  condition: []
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.hyunjun_mosquitto_protector
