##########################################################
# Sonos Automation
##########################################################
# Play Sonos when motion is detected
- alias: Play Sonos when motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.room_door_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: state
    entity_id: media_player.playroom
    state: 'paused'
  - condition: state
    entity_id: binary_sensor.room_bed_sleep
    state: 'off'
  - condition: time
    after: '11:00:00'
    before: '20:00:00'
  - condition: state
    entity_id: switch.music_auto_play
    state: 'on'
  action:
  - service: script.sonos_play_random

# Play Sonos when motion is detected
- alias: Play Sonos when motion is detected at night
  trigger:
  - platform: state
    entity_id: binary_sensor.room_door_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: state
    entity_id: media_player.playroom
    state: 'paused'
  - condition: state
    entity_id: binary_sensor.room_bed_sleep
    state: 'off'
  - condition: time
    after: '20:00:00'
    before: '03:00:00'
  - condition: state
    entity_id: switch.music_auto_play
    state: 'on'
  action:
  - service: script.sonos_play_jazz

# Update Sonos Playlist from Favorite
- alias: Update Sonos Playlist
  trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: '06:00:00'
  action:
  - service: rest_command.update_sonos_playlist

# Select source from playlist
- alias: Select Source from Playlist
  trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: input_select
      service: select_option
  condition:
  - condition: state
    entity_id: switch.music_auto_play
    state: 'on'
  action:
  - service: script.sonos_play_specific_song

# Play Sonos night song when sleep sensor is detected
- alias: Play Sonos night song when sleep sensor is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: time
    after: '20:00:00'
    before: '05:00:00'
  - condition: state
    entity_id: switch.mibox
    state: 'off'
  action:
  - service: script.sonos_play_sleep_song

# Stop Sonos 30 minutes after sleep sensor is detected
- alias: Stop Sonos 30 minutes after sleep sensor is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
    to: 'on'
    for:
      minutes: 30
  - platform: state
    entity_id: media_player.playroom
    to: 'playing'
    for:
      minutes: 30
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: state
    entity_id: binary_sensor.room_bed_sleep
    state: 'on'
  - condition: state
    entity_id: media_player.playroom
    state: 'playing'
  action:
  - service: media_player.media_stop
    data_template:
      entity_id: media_player.playroom
  - service: switch.turn_off
    data:
      entity_id: switch.music_auto_play

# Turn on Music Auto Play every 7AM
- alias: Turn on Music Auto Play every 7AM
  trigger:
  - platform: time
    at: "07:00:00"
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.music_auto_play

# Play Song In The Morning
- alias: Play Song in the Morning
  trigger:
  - platform: time
    at: "08:00:00"
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
    to: 'off'
  - platform: state
    entity_id: binary_sensor.room_door_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: state
    entity_id: media_player.playroom
    state: 'paused'
  - condition: state
    entity_id: switch.music_auto_play
    state: 'on'
  - condition: time
    after: '07:00:00'
    before: '11:00:00'
  action:
  - service: script.turn_on
    data:
      entity_id: script.sonos_play_kpop_top100

# Stop Sonos when I am away
- alias: Stop Sonos when I am away
  trigger:
  - platform: state
    entity_id: media_player.playroom
    to: 'playing'
  - platform: state
    entity_id: binary_sensor.yunhan_android
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'off'
  - condition: state
    entity_id: media_player.playroom
    state: 'playing'
  action:
  - service_template: media_player.media_stop
    data_template:
      entity_id: media_player.playroom
  - service: switch.turn_on
    data:
      entity_id: switch.music_auto_play
