##########################################################
# MI Air Purifier
##########################################################
- alias: mqtt_mi_air_purifier_st
  hide_entity: true
  trigger:
  - platform: mqtt
    topic: smartthings/Mi Air Purifier/switch
  condition:
  - condition: template
    value_template: "{{ states('binary_sensor.mi_air_purifier') != states('fan.mi_air_purifier') }}"
  action:
  - data_template:
      entity_id: fan.mi_air_purifier
    service_template:  >
      fan.turn_{{ trigger.payload }}

- alias: mqtt_mi_air_purifier_ha
  hide_entity: true
  trigger:
  - platform: state
    entity_id: fan.mi_air_purifier
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: fan.mi_air_purifier
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Mi Air Purifier/switch
      payload: >
        {% if is_state('fan.mi_air_purifier', 'on') %}on{% else %}off{% endif %}


##########################################################
# MI Stading Fan
##########################################################
- alias: mqtt_mi_standing_fan_st
  hide_entity: true
  trigger:
  - platform: mqtt
    topic: smartthings/Mi Standing Fan/switch
  condition:
  - condition: template
    value_template: "{{ states('binary_sensor.mi_standing_fan') != states('fan.mi_standing_fan') }}"
  action:
  - data_template:
      entity_id: fan.mi_standing_fan
    service_template:  >
      fan.turn_{{ trigger.payload }}

- alias: mqtt_mi_standing_fan_ha
  hide_entity: true
  trigger:
  - platform: state
    entity_id: fan.mi_standing_fan
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: fan.mi_standing_fan
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Mi Standing Fan/switch
      payload: >
        {% if is_state('fan.mi_standing_fan', 'on') %}on{% else %}off{% endif %}

##########################################################
# Samsung Air Conditioner
##########################################################
- alias: mqtt_samsung_air_conditioner_st
  hide_entity: true
  trigger:
  - platform: mqtt
    topic: smartthings/Samsung Air Conditioner/switch
  condition: []
  action:
  - service_template: >
      script.script_turn_{% if is_state('switch.samsung_air_conditioner', 'on') %}on{% else %}off{% endif %}_my_room_ac
