- alias: Welcome Lamp ON with BT
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_bt_presence
      from: 'off'
      to: 'on'
  condition:
    - condition: or
      conditions:
      - condition: template
        value_template: "{{ states('sensor.room_illuminance') | int < 100 }}"
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: template
        value_template: "{{ states('sensor.gateway_illumination') < '300' }}"
      - condition: state
        entity_id: cover.window_curtain
        state: 'closed'
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightwelcome

- alias: Welcome Lamp ON with Illuminance
  trigger:
    - platform: numeric_state
      entity_id: sensor.gateway_illumination
      below: 300
  condition:
    - condition: state
      entity_id: binary_sensor.yunhan_bt_presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightwelcome

- alias: Door Motion Lamp ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_door_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ states('sensor.gateway_illumination') < '300' }}"
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightdeskmotion

- alias: Bed Motion Lamp ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ states('sensor.gateway_illumination') < '300' }}"
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightbedmotion

- alias: Bed Motion Lamp OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_motion
      from: 'on'
      to: 'off'
  condition:
    - condition: template
      value_template: "{{ states('sensor.gateway_illumination') < '300' }}"
    - condition: state
      entity_id: binary_sensor.room_door_motion
      state: 'on'
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightdeskmotion

- alias: Before Sleep ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ states('sensor.gateway_illumination') < '300' }}"
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightbeforesleep

- alias: Sleep ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      to: 'on'
      for:
        minutes: 20
  condition:
    - condition: template
      value_template: "{{ states('sensor.gateway_illumination') < '300' }}"
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff

- alias: Welcome Lamp OFF with Illuminance
  trigger:
    - platform: numeric_state
      entity_id: sensor.gateway_illumination
      above: 300
  condition: []
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff

- alias: Welcome Lamp OFF with BT
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_bt_presence
      from: 'on'
      to: 'off'
  condition: []
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff

#- alias: Heartbeat on Gateway
#  trigger:
#    platform: time_pattern
#    seconds: '/10'
#  condition: []
#  action:
#    - service: light.turn_on
#      data:
#        entity_id: light.gateway_light
#        brightness: 10
#        color_name: "blue"
#    - service: light.turn_off
#      data:
#        entity_id: light.gateway_light
