- alias: Turn On Monitor When Desktop/Macbook Is Turned ON
  trigger:
  - platform: state
    entity_id: binary_sensor.yunhan_desktop
    to: 'on'
  - platform: state
    entity_id: binary_sensor.yunhan_macbook
    to: 'on'
  - platform: state
    entity_id: binary_sensor.yunhan_bt_presence
    to: 'on'
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
    to: 'off'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.yunhan_desktop
      state: 'on'
    - condition: state
      entity_id: binary_sensor.yunhan_macbook
      state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.main_pc_monitor
      state: 'off'
    - condition: state
      entity_id: switch.sub_pc_monitor
      state: 'off'
  - condition: state
    entity_id: binary_sensor.room_bed_sleep
    state: 'off'
  action:
  - service_template: switch.turn_on
    data:
      entity_id: switch.main_pc_monitor
  - service_template: switch.turn_on
    data:
      entity_id: switch.sub_pc_monitor

- alias: Turn Off Monitor When Desktop/Macbook Is Turned OFF
  trigger:
  - platform: state
    entity_id: binary_sensor.yunhan_desktop
    to: 'off'
  - platform: state
    entity_id: binary_sensor.yunhan_macbook
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_desktop
    state: 'off'
  - condition: state
    entity_id: binary_sensor.yunhan_macbook
    state: 'off'
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.main_pc_monitor
      state: 'on'
    - condition: state
      entity_id: switch.sub_pc_monitor
      state: 'on'
  action:
  - service_template: switch.turn_off
    data:
      entity_id: switch.main_pc_monitor
  - service_template: switch.turn_off
    data:
      entity_id: switch.sub_pc_monitor


- alias: Turn Off Monitor with Bluetooth Presence
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_bt_presence
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.main_pc_monitor
        state: 'on'
      - condition: state
        entity_id: switch.sub_pc_monitor
        state: 'on'
  action:
    - service_template: switch.turn_off
      data:
        entity_id: switch.main_pc_monitor
    - service_template: switch.turn_off
      data:
        entity_id: switch.sub_pc_monitor

- alias: Turn Off Monitor When I Go To Bed
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      to: 'on'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.main_pc_monitor
        state: 'on'
      - condition: state
        entity_id: switch.sub_pc_monitor
        state: 'on'
  action:
    - service_template: switch.turn_off
      data:
        entity_id: switch.main_pc_monitor
    - service_template: switch.turn_off
      data:
        entity_id: switch.sub_pc_monitor
