- alias: Turn On/Off Monitor When Desktop Is Turned ON/OFF
  trigger:
  - platform: state
    entity_id: binary_sensor.yunhan_desktop
  action:
  - service_template: switch.turn_{{ trigger.to_state.state }}
    data:
      entity_id: switch.pc_monitor

- alias: Turn On Monitor After Seating
  trigger:
    - platform: state
      entity_id: binary_sensor.desk_chair
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.pc_monitor
      state: 'off'
  action:
    - service_template: switch.turn_on
      data:
        entity_id: switch.pc_monitor

- alias: Turn On Monitor When Motion Is Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.room_door_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.pc_monitor
      state: 'off'
    - condition: state
      entity_id: binary_sensor.yunhan_desktop
      state: 'on'
  action:
    - service_template: switch.turn_on
      data:
        entity_id: switch.pc_monitor

- alias: Turn Off Monitor After Leaving
  trigger:
    - platform: state
      entity_id: binary_sensor.desk_chair
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: switch.pc_monitor
      state: 'on'
  action:
    - service_template: switch.turn_off
      data:
        entity_id: switch.pc_monitor

- alias: Turn Off Monitor After I Go To Bed
  trigger:
    - platform: state
      entity_id: binary_sensor.bed_switch
      to: 'on'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: switch.pc_monitor
      state: 'on'
  action:
    - service_template: switch.turn_off
      data:
        entity_id: switch.pc_monitor
