##########################################################
# Virtual Presence
##########################################################
- alias: Minjun's Android Presence to ST
  trigger:
  - platform: state
    entity_id: device_tracker.minjun_android
  - platform: time_pattern
    minutes: "/5"
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Minjun's Presence/presence
      payload: >
        {% if is_state('device_tracker.minjun_android', 'home') %}present{% else %}not present{% endif %}

- alias: Hyunjun's Android Presence to ST
  trigger:
  - entity_id: device_tracker.hyunjun_android
    platform: state
  - platform: time_pattern
    minutes: "/5"
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Hyunjun's Presence/presence
      payload: >
        {% if is_state('device_tracker.hyunjun_android', 'home') %}present{% else %}not present{% endif %}

- alias: Jiyeon's iPhone Presence to ST
  trigger:
  - entity_id: device_tracker.mom_iphone
    platform: state
  - platform: time_pattern
    minutes: "/5"
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Mom's Presence/presence
      payload: >
        {% if is_state('device_tracker.mom_iphone', 'home') %}present{% else %}not present{% endif %}

- alias: Granma's Android Presence to ST
  trigger:
  - entity_id: device_tracker.hyunjun_android
    platform: state
  - platform: time_pattern
    minutes: "/5"
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: smartthings/Grandma's Presence/presence
      payload: >
        {% if is_state('device_tracker.grandma_android', 'home') %}present{% else %}not present{% endif %}

- alias: SPBEAR's Desktop Presence to ST
  trigger:
  - entity_id: device_tracker.spbear_desktop
    platform: state
  - platform: time_pattern
    minutes: "/5"
  condition: []
  action:
    - service: mqtt.publish
      data_template:
        topic: smartthings/Desktop PC/switch
        payload: >
          {% if is_state('device_tracker.spbear_desktop', 'home') %}on{% else %}off{% endif %}

- alias: SPBEAR's WiFi to ST
  trigger:
  - entity_id: device_tracker.yunhan_android
    platform: state
  condition: []
  action:
    - service: mqtt.publish
      data_template:
        topic: smartthings/Yunhan's WiFi/presence
        payload: >
          {% if is_state('device_tracker.yunhan_android', 'home') %}present{% else %}not present{% endif %}

- alias: Yunhan's HA to ST
  trigger:
  - entity_id: binary_sensor.yunhan_android
    platform: state
  - entity_id: binary_sensor.room_door_motion
    platform: state
  condition: []
  action:
    - service: mqtt.publish
      data_template:
        topic: smartthings/Yunhan's Presence/presence
        payload: >
          {% if is_state('binary_sensor.yunhan_android', 'on') %}present{% else %}not present{% endif %}
