- alias: Dehumidifier Control
  trigger:
    - platform: state
      entity_id: switch.mi_dehumidifier
  condition: []
  action:
    - service_template: shell_command.dehumidifier_{{ states('switch.mi_dehumidifier') }}

- alias: Turn On Humidifier
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_humidify
      below: 40
  condition:
    - condition: state
      entity_id: binary_sensor.yunhan_android
      state: 'on'
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.mi_humidifier
    - service: switch.turn_off
      data:
        entity_id: switch.mi_dehumidifier

- alias: Turn On Dehumidifier
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_humidify
      above: 70
    - platform: state
      entity_id: binary_sensor.window_sensor
      state: 'off'
    - platform: state
      entity_id: binary_sensor.room_door_status
      state: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.yunhan_android
      state: 'on'
    - condition: state
      entity_id: binary_sensor.window_sensor
      state: 'off'
    - condition: state
      entity_id: binary_sensor.room_door_status
      state: 'off'
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.mi_humidifier
    - service: switch.turn_on
      data:
        entity_id: switch.mi_dehumidifier

- alias: Notify Humidifier Depth is Low
  trigger:
    - platform: numeric_state
      entity_id: sensor.mi_humidifier_depth
      below: 20
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: binary_sensor.yunhan_android
      state: 'on'
  action:
    - service: notify.home
      data_template:
        message: "🚰 가습기에 물이 떨어졌습니다. 물을 채워주세요."
