- alias: Fan to Bed When I Arrived At Home
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_android
      from: 'off'
      to: 'on'
  condition: []
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.mi_standing_fan
    - service: script.turn_on
      data:
        entity_id: script.fan_to_desk

- alias: Fan to Bed When Bed Is Occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'off'
      to: 'on'
      for:
        seconds: 20
  condition:
    - condition: state
      entity_id: switch.fan_direction_to_desk
      state: 'on'
    - condition: state
      entity_id: fan.mi_standing_fan
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.room_temperature
      above: 22.0
  action:
    - service: script.turn_on
      data:
        entity_id: script.fan_to_bed

- alias: Fan to Bed When Bed Is Not Occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'on'
      to: 'off'
      for:
        seconds: 20
  condition:
    - condition: state
      entity_id: switch.fan_direction_to_desk
      state: 'off'
    - condition: state
      entity_id: fan.mi_standing_fan
      state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.fan_to_desk

- alias: Fan to Desk When Chair Is Occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.desk_chair
      from: 'off'
      to: 'on'
      for:
        seconds: 20
  condition:
    - condition: state
      entity_id: switch.fan_direction_to_desk
      state: 'off'
    - condition: state
      entity_id: fan.mi_standing_fan
      state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.fan_to_desk

- alias: Fan to Sleep
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'off'
      to: 'on'
      for:
        minutes: 120
  condition:
    - condition: state
      entity_id: fan.mi_standing_fan
      state: 'on'
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.mi_standing_fan
