- alias: Turn off Livingroom TV Afther the Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: group.people
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.livingroom_tv
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.livingroom_tv

- alias: Turn off Livingroom Lights Afther the Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: group.people
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.livingroom_light
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.livingroom_light

- alias: Turn off Livingroom Sub Lights Afther the Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: group.people
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.livingroom_sub_light
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.livingroom_sub_light
