- alias: Notify Entrance door's change
  trigger:
  - platform: state
    entity_id: binary_sensor.entrance_door
    to: 'on'
  condition: []
  action:
  - service: notify.me
    data_template:
      title: 'Notify'
      message: "🚪문이 열렸습니다\r
        {% if is_state('binary_sensor.passage_motion', 'on') %}🏃 복도에 움직임이 있어요\r🏃 누군가 나간 것일 수 있어요{% else %}🧍 복도에 움직임이 없어요{% endif %}"
