- alias: Notify Yunhan's presence
  trigger:
  - platform: state
    entity_id: binary_sensor.yunhan_android
  condition: []
  action:
  - service: notify.me
    data_template:
      message: "
        {% if trigger.to_state.state == 'on' %}🧑🏻 아빠가 집에 왔어요{% else %}🧑🏻 아빠가 집을 떠났어요{% endif %}\r
        ---------\r
        {% if is_state('binary_sensor.yunhan_android', 'on') %}🧑🏻 아빠는 집에 있어요{% else %}🚘 아빠는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.mom_iphone', 'on') %}👩🏻 엄마는 집에 있어요{% else %}🚘 엄마는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.hyunjun_android', 'on') %}👦🏻 현준이는 집에 있어요{% else %}🚲 현준이는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.minjun_android', 'on') %}👦🏻 민준이는 집에 있어요{% else %}🚲 민준이는 집에 없어요{% endif %}"

- alias: Notify Mom's presence
  trigger:
  - platform: state
    entity_id: binary_sensor.mom_iphone
  condition: []
  action:
  - service: notify.me
    data_template:
      message: "
        {% if trigger.to_state.state == 'on' %}👩🏻 엄마가 집에 왔어요{% else %}👩🏻 엄마가 집을 떠났어요{% endif %}\r
        ---------\r
        {% if is_state('binary_sensor.yunhan_android', 'on') %}🧑🏻 아빠는 집에 있어요{% else %}🚘 아빠는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.mom_iphone', 'on') %}👩🏻 엄마는 집에 있어요{% else %}🚘 엄마는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.hyunjun_android', 'on') %}👦🏻 현준이는 집에 있어요{% else %}🚲 현준이는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.minjun_android', 'on') %}👦🏻 민준이는 집에 있어요{% else %}🚲 민준이는 집에 없어요{% endif %}"

- alias: Notify Hyunjun's presence
  trigger:
  - platform: state
    entity_id: binary_sensor.hyunjun_android
  condition: []
  action:
  - service: notify.me
    data_template:
      message: "
        {% if trigger.to_state.state == 'on' %}👦🏻 현준이가 집에 왔어요{% else %}👦🏻 현준이가 집을 떠났어요{% endif %}\r
        ---------\r
        {% if is_state('binary_sensor.yunhan_android', 'on') %}🧑🏻 아빠는 집에 있어요{% else %}🚘 아빠는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.mom_iphone', 'on') %}👩🏻 엄마는 집에 있어요{% else %}🚘 엄마는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.hyunjun_android', 'on') %}👦🏻 현준이는 집에 있어요{% else %}🚲 현준이는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.minjun_android', 'on') %}👦🏻 민준이는 집에 있어요{% else %}🚲 민준이는 집에 없어요{% endif %}"

- alias: Notify Minjun's presence
  trigger:
  - platform: state
    entity_id: binary_sensor.minjun_android
  condition: []
  action:
  - service: notify.me
    data_template:
      message: "
        {% if trigger.to_state.state == 'on' %}👦🏻 민준이가 집에 왔어요{% else %}👦🏻 민준이가 집을 떠났어요{% endif %}\r
        ---------\r
        {% if is_state('binary_sensor.yunhan_android', 'on') %}🧑🏻 아빠는 집에 있어요{% else %}🚘 아빠는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.mom_iphone', 'on') %}👩🏻 엄마는 집에 있어요{% else %}🚘 엄마는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.hyunjun_android', 'on') %}👦🏻 현준이는 집에 있어요{% else %}🚲 현준이는 집에 없어요{% endif %}\r
        {% if is_state('binary_sensor.minjun_android', 'on') %}👦🏻 민준이는 집에 있어요{% else %}🚲 민준이는 집에 없어요{% endif %}"

- alias: Notify Bed Status
  trigger:
  - platform: state
    entity_id: binary_sensor.room_bed_sleep
  condition: []
  action:
  - service: notify.me
    data_template:
      message: "
        {% if trigger.to_state.state == 'on' %}🛌🏽 침대에 누웠습니다 🟢{% else %}🛏️ 침대에서 일어났습니다 🔴{% endif %}"

- alias: Notify Hyunjun Desktop Status
  trigger:
  - platform: state
    entity_id: binary_sensor.hyunjun_desktop
  condition: []
  action:
  - service: notify.home
    data_template:
      message: "
        {% if trigger.to_state.state == 'on' %}👦🏻 현준이가 🖥️ 컴퓨터를 🟢 켰어요{% else %}👦🏻 현준이가 🖥️ 컴퓨터를 🔴 껐어요{% endif %}"

- alias: Notify Minjun Desktop Status
  trigger:
  - platform: state
    entity_id: binary_sensor.minjun_desktop
  condition: []
  action:
  - service: notify.home
    data_template:
      message: "
        {% if trigger.to_state.state == 'on' %}👦🏻 민준이가 🖥️ 컴퓨터를 🟢 켰어요{% else %}👦🏻 민준이가 🖥️ 컴퓨터를 🔴 껐어요{% endif %}"
