- alias: Turn On Heating Control Below 20.5c
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_temperature
      below: 20.5
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.yunhan_android
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.heating_control
      state: 'off'
    - condition: state
      entity_id: binary_sensor.yunhan_android
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.room_temperature
      below: 20.5
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.heating_control

- alias: Turn On Heating Control Below 19.0c with Absence
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_temperature
      below: 19.0
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: switch.heating_control
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.heating_control

- alias: Turn Off Heating Control Above 20.5c
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_temperature
      above: 20.5
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: switch.heating_control
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.heating_control

- alias: Turn Off Heating Control Above 22.0c
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_temperature
      above: 22.0
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: switch.heating_control
      state: 'on'
    - condition: state
      entity_id: binary_sensor.yunhan_android
      state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.heating_control


- alias: Turn Off When Leaving
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_android
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.heating_control
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.room_temperature
      above: 19.0
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.heating_control
