#- alias: Clean my room in my absence
#  trigger:
#  - platform: time
#    at: '11:00:00'
#  condition:
#  - condition: state
#    entity_id: binary_sensor.yunhan_android
#    state: 'off'
#  - condition: state
#    entity_id: binary_sensor.room_door_status
#    state: 'on'
#  action:
#  - service: script.turn_on
#    data:
#      entity_id: script.clean_myroom

#- alias: Clean all rooms in an absence
#  trigger:
#  - platform: time
#    at: '12:30:00'
#  condition:
#  - condition: state
#    entity_id: group.people
#    state: 'off'
#  action:
#  - service: script.turn_on
#    data:
#      entity_id: script.clean_kitchen


- alias: Clean all rooms everyday
  trigger:
  - platform: time
    at: '08:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  action:
  - service: script.turn_on
    data:
      entity_id: script.clean_all

- alias: Report the error of vaccum machine to LINE
  trigger:
  - platform: state
    entity_id: vacuum.mi_robot_vacuum
    to: 'error'
  condition: []
  action:
  - service: notify.home
    data:
      title: 'Notify'
      message: "🤖🤖🤖\r청소기에 문제가 생겼습니다.\r청소기를 확인해 주세요."
