- alias: Restroom Light ON
  trigger:
    - platform: state
      entity_id: binary_sensor.restroom_door_status
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.restroom_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.restroom_light
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.restroom_light
    - service: switch.turn_on
      data:
        entity_id: switch.restroom_fan

- alias: Restroom Fan ON
  trigger:
    - platform: numeric_state
      entity_id: sensor.restroom_humidity
      above: 65.0
    - platform: state
      entity_id: binary_sensor.restroom_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.restroom_fan
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.restroom_fan

- alias: Restroom Light OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.restroom_motion
      from: 'on'
      to: 'off'
      for:
          minutes: 10
  condition:
    - condition: state
      entity_id: switch.restroom_light
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.restroom_light

- alias: Restroom Fan OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.restroom_motion
      from: 'on'
      to: 'off'
      for:
          minutes: 10
    - platform: numeric_state
      entity_id: sensor.restroom_humidity
      below: 65.0
  condition:
    - condition: state
      entity_id: switch.restroom_fan
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.restroom_humidity
      below: 65.0
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.restroom_fan
