- alias: Welcome Lamp ON with BT
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_bt_presence
      from: 'off'
      to: 'on'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: numeric_state
        entity_id: sensor.light_sensor
        below: 10
      - condition: state
        entity_id: cover.window_curtain
        state: 'closed'
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightwelcome

- alias: Welcome Lamp ON with Illuminance
  trigger:
    - platform: numeric_state
      entity_id: sensor.light_sensor
      below: 10
  condition:
    - condition: state
      entity_id: binary_sensor.yunhan_bt_presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightwelcome

- alias: Door Motion Lamp ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_door_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.light_sensor
      below: 10
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightdeskmotion

- alias: Bed Motion Lamp ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.light_sensor
      below: 10
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightbedmotion

- alias: Bed Motion Lamp OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_motion
      from: 'on'
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.light_sensor
      below: 10
    - condition: state
      entity_id: binary_sensor.room_door_motion
      state: 'on'
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightdeskmotion

- alias: Before Sleep ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'off'
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.light_sensor
      below: 10
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightbeforesleep

- alias: Sleep ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      to: 'on'
      for:
        minutes: 5
  condition: []
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff

- alias: Welcome Lamp OFF with Illuminance
  trigger:
    - platform: numeric_state
      entity_id: sensor.light_sensor
      above: 10
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: binary_sensor.desk_chair
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff

- alias: Welcome Lamp OFF with BT
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_bt_presence
      from: 'on'
      to: 'off'
  condition: []
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff

- alias: Passage Motion Lamp ON
  trigger:
    - platform: state
      entity_id: binary_sensor.passage_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entrance_door
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.passage_light
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.passage_light

- alias: Passage Motion Lamp OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.passage_motion
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: switch.passage_light
      state: 'on'
    - condition: state
      entity_id: binary_sensor.passage_motion
      state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.passage_light

- alias: Livingroom Sublight ON
  trigger:
    - platform: state
      entity_id: binary_sensor.passage_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entrance_door
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.livingroom_light
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.livingroom_sub_light


- alias: Night Livingroom
  trigger:
    - platform: time
      at: '23:00:00'
  condition: []
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.night_livingroom

- alias: Goodbye Kids
  trigger:
    - platform: time
      at: '23:30:00'
  condition: []
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.goodnight_kids

- alias: Livingroom Sub Light OFF when Livingroom Light Turned On
  trigger:
    - platform: state
      entity_id: switch.livingroom_light
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.livingroom_sub_light
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.livingroom_sub_light

- alias: Livingroom Sub Light On when Livingroom Light Turned On
  trigger:
    - platform: state
      entity_id: switch.livingroom_sub_light
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.livingroom_light
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.livingroom_light

- alias: Livingroom Sub Light OFF
  trigger:
    - platform: state
      entity_id: switch.livingroom_sub_light
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '23:00:00'
      before: '07:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.livingroom_sub_light

- alias: Minjun Stand Light OFF
  trigger:
    - platform: state
      entity_id: switch.minjun_stand_lamp
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '23:30:00'
      before: '07:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.minjun_stand_lamp

- alias: Minjun Room Light OFF
  trigger:
    - platform: state
      entity_id: switch.minjun_room_light
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '23:30:00'
      before: '07:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.minjun_room_light

- alias: Hyunjun Room Light OFF
  trigger:
    - platform: state
      entity_id: switch.hyunjun_room_light
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '23:30:00'
      before: '07:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.hyunjun_room_light

- alias: Hyunjun Garage Light OFF
  trigger:
    - platform: state
      entity_id: switch.hyunjun_garage_light
      to: 'on'
      for:
        minutes: 10
  condition: []
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.hyunjun_garage_light

- alias: Kitchen Light OFF
  trigger:
    - platform: state
      entity_id: switch.kitchen_light
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '23:00:00'
      before: '07:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_light

- alias: Kitchen Sub Light OFF
  trigger:
    - platform: state
      entity_id: switch.kitchen_sub_light
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '23:00:00'
      before: '07:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_sub_light

- alias: Kitchen Table Light OFF
  trigger:
    - platform: state
      entity_id: switch.table_light
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '23:00:00'
      before: '07:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.table_light
