- alias: Welcome Lamp ON with BT
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_bt_presence
      from: 'off'
      to: 'on'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: numeric_state
        entity_id: sensor.light_sensor
        below: 10
      - condition: state
        entity_id: cover.window_curtain
        state: 'closed'
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightwelcome

- alias: Welcome Lamp ON with Illuminance
  trigger:
    - platform: numeric_state
      entity_id: sensor.light_sensor
      below: 10
  condition:
    - condition: state
      entity_id: binary_sensor.yunhan_bt_presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightwelcome

- alias: Door Motion Lamp ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_door_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.light_sensor
      below: 10
    - condition: state
      entity_id: binary_sensor.room_bed_sleep
      state: 'off'
    - condition: state
      entity_id: light.desk_lamp
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightdeskmotion

- alias: Before Sleep ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      from: 'off'
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.light_sensor
      below: 10
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightbeforesleep

- alias: Sleep ON
  trigger:
    - platform: state
      entity_id: binary_sensor.room_bed_sleep
      to: 'on'
      for:
        minutes: 10
  condition: []
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff

- alias: Welcome Lamp OFF with Illuminance
  trigger:
    - platform: numeric_state
      entity_id: sensor.light_sensor
      above: 10
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: binary_sensor.desk_chair
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff

- alias: Welcome Lamp OFF with BT
  trigger:
    - platform: state
      entity_id: binary_sensor.yunhan_bt_presence
      from: 'on'
      to: 'off'
  condition: []
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightoff
