- alias: Clean my room
  trigger:
  - entity_id: binary_sensor.yunhan_android
    platform: state
    to: 'off'
    for:
      minutes: 20
  - entity_id: binary_sensor.minjun_android
    platform: state
    to: 'off'
    for:
      minutes: 20
  - entity_id: binary_sensor.hyunjun_android
    platform: state
    to: 'off'
    for:
      minutes: 20
  - entity_id: binary_sensor.mom_iphone
    platform: state
    to: 'off'
    for:
      minutes: 20
  - entity_id: binary_sensor.grandma_android
    platform: state
    to: 'off'
    for:
      minutes: 20
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'off'
  - condition: state
    entity_id: binary_sensor.minjun_android
    state: 'off'
  - condition: state
    entity_id: binary_sensor.hyunjun_android
    state: 'off'
  - condition: state
    entity_id: binary_sensor.mom_iphone
    state: 'off'
  - condition: state
    entity_id: binary_sensor.grandma_android
    state: 'off'
  action:
  - service: script.turn_on
    data:
      entity_id: script.clean_myroom

- alias: Clean Kitchen
  trigger:
  - entity_id: binary_sensor.yunhan_android
    platform: state
    to: 'off'
    for:
      minutes: 40
  - entity_id: binary_sensor.minjun_android
    platform: state
    to: 'off'
    for:
      minutes: 40
  - entity_id: binary_sensor.hyunjun_android
    platform: state
    to: 'off'
    for:
      minutes: 40
  - entity_id: binary_sensor.mom_iphone
    platform: state
    to: 'off'
    for:
      minutes: 40
  - entity_id: binary_sensor.grandma_android
    platform: state
    to: 'off'
    for:
      minutes: 40
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'off'
  - condition: state
    entity_id: binary_sensor.minjun_android
    state: 'off'
  - condition: state
    entity_id: binary_sensor.hyunjun_android
    state: 'off'
  - condition: state
    entity_id: binary_sensor.mom_iphone
    state: 'off'
  - condition: state
    entity_id: binary_sensor.grandma_android
    state: 'off'
  action:
  - service: script.turn_on
    data:
      entity_id: script.clean_kitchen
