- alias: Turn On Desk Light
  trigger:
    - platform: state
      entity_id: binary_sensor.desk_chair
      to: 'on'
  condition:
    - condition: state
      entity_id: light.desk_lamp
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lightdeskmotion

- alias: Turn Off Desk Light
  trigger:
    - platform: state
      entity_id: binary_sensor.desk_chair
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: light.desk_lamp
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.light_sensor
      above: 10
  action:
    - service: light.turn_off
      data:
        entity_id: light.desk_lamp
