- alias: Clean all rooms after a vacancy
  trigger:
  - entity_id: binary_sensor.yunhan_android
    platform: state
    to: 'off'
    for:
      minutes: 20
  - entity_id: group.people
    platform: state
    to: 'off'
    for:
      minutes: 20
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'off'
  - condition: state
    entity_id: group.people
    state: 'off'
  action:
  - service: script.turn_on
    data:
      entity_id: script.clean_all


- alias: Clean all rooms on weekend
  trigger:
  - platform: time
    at: "09:05:00"
  condition:
  - condition: state
    entity_id: binary_sensor.yunhan_android
    state: 'on'
  - condition: time
    weekday:
      - sat
      - sun
  action:
  - service: script.turn_on
    data:
      entity_id: script.clean_all
