##########################################################
# Virtual Presence
##########################################################
- platform: mqtt
  state_topic: smartthings/Minjun's Presence/presence
  name: minjun_android
  payload_on: 'present'
  payload_off: 'not present'

- platform: mqtt
  state_topic: smartthings/Hyunjun's Presence/presence
  name: hyunjun_android
  payload_on: 'present'
  payload_off: 'not present'

- platform: mqtt
  state_topic: smartthings/Mom's Presence/presence
  name: mom_iphone
  payload_on: 'present'
  payload_off: 'not present'

- platform: workday
  name: workday
  country: Korea
  workdays: [mon, tue, wed, thu, fri]

- platform: mqtt
  state_topic: smartthings/Grandma's Presence/presence
  name: grandma_android
  payload_on: 'present'
  payload_off: 'not present'

##########################################################
# Yunhan's Presence
##########################################################
- platform: mqtt
  state_topic: smartthings/Yunhan's Bluetooth/presence
  name: yunhan_bt_presence
  payload_on: 'present'
  payload_off: 'not present'

- platform: mqtt
  state_topic: smartthings/Yunhan's WiFi/presence
  name: yunhan_wifi_presence
  payload_on: 'present'
  payload_off: 'not present'

- platform: template
  sensors:
    yunhan_android:
      friendly_name: Yunhan's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{{is_state('device_tracker.yunhan_android', 'home') or is_state('binary_sensor.yunhan_bt_presence', 'on') }}"

    washingmachine:
      friendly_name: Washing Machine
      icon_template: "mdi:washing-machine"
      value_template: "{{ float(states.switch.washingmachine.attributes.power) > 2.0 }}"

##########################################################
# Desktop
##########################################################
- platform: mqtt
  state_topic: smartthings/Desktop PC/switch
  name: yunhan_desktop
  payload_on: 'present'
  payload_off: 'not present'

- platform: mqtt
  state_topic: smartthings/Yunhan Macbook/switch
  name: yunhan_macbook
  payload_on: 'present'
  payload_off: 'not present'

- platform: mqtt
  state_topic: smartthings/Hyunjun Desktop/switch
  name: hyunjun_desktop
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: smartthings/Minjun Desktop/switch
  name: minjun_desktop
  payload_on: 'on'
  payload_off: 'off'

- platform: template
  sensors:
    room_bed_sleep:
      friendly_name: Room Bed Sleep
      value_template: "{{is_state('switch.sleep_sensor', 'on') }}"

- platform: mqtt
  state_topic: bt-gateway/projector/presence
  name: screen_projector
  payload_on: 'True'
  payload_off: 'False'

- platform: mqtt
  state_topic: smartthings/Mi Air Purifier/switch
  name: Mi Air Purifier
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/BMW 04184
  name: BMW
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/spbear의 AirPods
  name: AirPods
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/Gear S3 (D578)
  name: Gear S3
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/Gear Fit2 Pro (6C25)
  name: Gear Fit2 Pro
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/Galaxy Watch Active2(CCA7)
  name: Watch Active2
  payload_on: 'on'
  payload_off: 'off'
