- platform: template
  sensors:
    yunhan_desktop:
      friendly_name: Yunhan's Desktop PC
      icon_template: "mdi:monitor"
      value_template: "{{ is_state('device_tracker.spbear_desktop', 'home')}}"

    yunhan_android:
      friendly_name: Yunhan's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{{ is_state('sensor.yunhans_gs8', 'present') or is_state('device_tracker.yunhan_android', 'home') }}"

    minjun_android:
      friendly_name: Minjun's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{{ is_state('device_tracker.minjun_android', 'home')}}"

    hyunjun_android:
      friendly_name: Hyunjun's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{{ is_state('device_tracker.hyunjun_android', 'home')}}"

    jiyeon_iphone:
      friendly_name: Jiyeon's iPhone
      icon_template: "mdi:cellphone-iphone"
      value_template: "{{ is_state('device_tracker.jiyeon_iphone', 'home')}}"

- platform: mqtt
  state_topic: smartthings/Main Door/contact
  name: Main Door Status
  payload_on: 'open'
  payload_off: 'closed'

- platform: mqtt
  state_topic: smartthings/Daddy's Room Door Sensor/motion
  name: Room Door Motion
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  state_topic: smartthings/Daddy's Room Bed Sensor/motion
  name: Room Bed Motion
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  state_topic: smartthings/Passage Motion Sensor/motion
  name: Passage Motion
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  state_topic: smartthings/Nokia Sleep/switch
  name: Room Bed Sleep
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: smartthings/Mi Standing Fan/switch
  name: Mi Standing Fan
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: smartthings/Mi Air Purifier/switch
  name: Mi Air Purifier
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: sonos/manual_stop
  name: Sonos Manual Stop
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/BMW 04184
  name: BMW
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/SPBEAR AirPods
  name: AirPods
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/Gear S3 (D578)
  name: Gear S3
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/Gear Fit2 Pro (6C25)
  name: Gear Fit2 Pro
  payload_on: 'on'
  payload_off: 'off'
