- platform: mqtt
  state_topic: bt-gateway/bt-presence/SPBEAR
  name: yunhan_bt_presence
  friendly_name: Yunhan's BT Presence
  icon_template: "mdi:cellphone-android"
  payload_on: 'present'
  payload_off: 'not present'

- platform: mqtt
  state_topic: smartthings/Yunhan's GS8/presence
  name: yunhan_gps_presence
  friendly_name: Yunhan's GPS Presence
  icon_template: "mdi:cellphone-android"
  payload_on: 'present'
  payload_off: 'not present'

- platform: template
  sensors:
    yunhan_desktop:
      friendly_name: Yunhan's Desktop PC
      icon_template: "mdi:monitor"
      value_template: "{{ is_state('device_tracker.spbear_desktop', 'home')}}"

    yunhan_android:
      friendly_name: Yunhan's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{{ is_state('binary_sensor.yunhan_gps_presence', 'on') or is_state('device_tracker.yunhan_android', 'home') or is_state('binary_sensor.yunhan_bt_presence', 'on') }}"

    minjun_android:
      friendly_name: Minjun's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{{ is_state('device_tracker.minjun_android', 'home')}}"

    hyunjun_android:
      friendly_name: Hyunjun's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{{ is_state('device_tracker.hyunjun_android', 'home')}}"

    mom_iphone:
      friendly_name: Mom's iPhone
      icon_template: "mdi:cellphone-iphone"
      value_template: "{{ is_state('device_tracker.mom_iphone', 'home')}}"

    grandma_android:
      friendly_name: Grandma's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{{ is_state('device_tracker.grandma_android', 'home')}}"

- platform: mqtt
  state_topic: smartthings/Main Door/contact
  name: Main Door Status
  payload_on: 'open'
  payload_off: 'closed'

- platform: mqtt
  state_topic: smartthings/Daddy's Room Door Sensor/motion
  name: Room Door Motion
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  state_topic: smartthings/Daddy's Room Bed Sensor/motion
  name: Room Bed Motion
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  state_topic: smartthings/Passage Motion Sensor/motion
  name: Passage Motion
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  state_topic: smartthings/Nokia Sleep/switch
  name: Room Bed Sleep
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: smartthings/Mi Standing Fan/switch
  name: Mi Standing Fan
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: smartthings/Mi Air Purifier/switch
  name: Mi Air Purifier
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/BMW 04184
  name: BMW
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/spbear의 AirPods
  name: AirPods
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/Gear S3 (D578)
  name: Gear S3
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  state_topic: mobile/yunhan/bluetooth/Gear Fit2 Pro (6C25)
  name: Gear Fit2 Pro
  payload_on: 'on'
  payload_off: 'off'
