homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Seoul
  # Customization file
  customize: !include customize.yaml
  customize_glob:
    "light.*":
      show_last_changed: true
      custom_ui_state_card: state-card-custom-ui
    "fan.*":
      show_last_changed: true
      custom_ui_state_card: state-card-custom-ui
    "vacuum.*":
      show_last_changed: true
      custom_ui_state_card: state-card-custom-ui
    "binary_sensor.*":
      show_last_changed: true
      custom_ui_state_card: state-card-custom-ui
    "switch.*":
      show_last_changed: true
      custom_ui_state_card: state-card-custom-ui
    "cover.*":
      show_last_changed: true
      custom_ui_state_card: state-card-custom-ui

logger:
  default: info
  logs:
    homeassistant.components.device_tracker: error
    homeassistant.components.xiaomi_aqara: debug
    homeassistant.event: debug
    homeassistant.components.alexa: debug
    homeassistant.components.intent_script: debug
    custom_components.fan.xiaomi_miio_fan: debug

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

alexa:

intent_script: !include alexa.yaml

customizer:
  custom_ui: local

# Track the sun
sun:

# Sensors
device_tracker: !include device_tracker.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

# Enables configuration UI
config:

mqtt:
  broker: !secret raspberrypi_ip
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

ifttt:
  key: !secret ifttt_key

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history: !include history.yaml
# exclude:
#   domains:
#     - automation
#   entities:
#     -

# View all events in a logbook
logbook:
  exclude:
    entities:
      - fan.mi_standing_fan
    domains:
      - group

# Enables a map showing the location of tracked devices
map:

# Text to speech
tts:
  platform: google
  language: 'ko'

# Cloud
cloud:

vacuum:
  - platform: xiaomi_miio
    name: "Mi Robot Vacuum"
    host: !secret xiaomi_robot_vacuum_ip
    token: !secret vacuum_token

fan:
  - platform: xiaomi_miio
    name: "Mi Air Purifier"
    #icon: mdi:weather-windy
    host: !secret xiaomi_air_purifier_myroom_ip
    token: !secret air_purifier_token

  - platform: xiaomi_miio_fan
    name: "Mi Standing Fan"
    host: !secret xiaomi_standing_fan_ip
    token: !secret fan_token

  - platform: xiaomi_miio
    name: "Living Room Mi Air Purifier"
    #icon: mdi:weather-windy
    host: !secret xiaomi_air_purifier_livingroom_ip
    token: !secret air_purifier_livingroom_token

  - platform: xiaomi_miio
    name: "Mi Humidifier"
    #icon: mdi:weather-windy
    host: !secret xiaomi_humidifier_ip
    token: !secret humidifier_token

cover:
  - platform: brunt
    username: !secret brunt_username
    password: !secret brunt_password

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_gateway_mac
      key: !secret gateway_token

remote:
  - platform: xiaomi_miio
    name: "Mi IR Controller"
    host: !secret xiaomi_ir_controller_ip
    token: !secret remote_token
    slot: 1
    timeout: 30
    hidden: true
    commands:
      turn_on_my_room_ac:
        command:
          - raw:Z6XTACkCAACWBgAAZREAADkjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEBAAAAAAEBAQEBAAAAAAEAAAAAAAEBAQAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAEBAAEAAAAAAA

      turn_off_my_room_ac:
        command:
           - raw:Z6XTACkCAACWBgAAmhEAAAEjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEBAAAAAAEBAQEBAAAAAAEAAAAAAAEBAQAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAAAAAEBAQEAAQEBAA

      set_my_room_24c:
        command:
          - raw:Z6XTACkCAACWBgAAZREAADkjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEBAAAAAAEBAQEBAAAAAAEAAAAAAAEBAQAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAEBAAEAAAAAAA

      set_my_room_25c:
        command:
          - raw:Z6XTACoCAACMBgAAfBEAACAjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEBAAAAAAEBAQEBAQAAAAEAAAAAAAEBAQAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAABAAAAAA

      set_my_room_26c:
        command:
          - raw:Z6XTACcCAACrBgAAnBEAAAIjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEBAAAAAAEBAQEBAAEAAAEAAAAAAAEBAQAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAEBAAAAAA

      set_my_room_27c:
        command:
          - raw:Z6XTACoCAACUBgAAfxEAAB4jAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEBAAAAAAEBAQEBAQEAAAEAAAAAAAEBAQAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAA

      power_gs1:
        command:
          - raw:Z6VHACQCAABLAgAAjwYAAL8IAACOEQAAYCMAAEyzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEBAQEBAQEBAQEBISEBAQEhAQEBAQEBIQEhISEhISFhNQEAAAAAAAAAAAAAZ6VHACQCAABLAgAAjwYAAL8IAACOEQAAYCMAAEyzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEBAQEBAQEBAQEBISEBAQEhAQEBAQEBIQEhISEhISFhNQE=

switch: !include switches.yaml

media_player:
  - platform: samsungtv
    host: !secret samsung_tv_ip
    port: 8001
    name: Livingroom TV
    mac: !secret livingroom_tv_mac
  - platform: androidtv
    host: !secret mibox_ip
    adb_server_ip: 127.0.0.1
    name: MIBOX
    apps:
      "netflix": "Netflix"
      "youtube": "Youtube"

history_graph:
  gr1:
    name: Temperature
    entities:
      - sensor.weather_temperature
      - sensor.room_temperature
    hours_to_show: 24
    refresh: 60
  gr2:
    name: Humidity
    entities:
      - sensor.weather_humidity
      - sensor.room_humidity
    hours_to_show: 24
    refresh: 60


group: !include groups.yaml
scene: !include scene.yaml

script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
rest_command: !include rest_command.yaml

input_select:
  sonos_playlist:
    name: What music do you want to play?
    options:
     - None
    initial: None
    icon: mdi:music
