default_view:
  name: Home
  view: yes
  icon: mdi:home
  entities:
    - group.weather
    - group.sensor
    - group.people
    - group.main_door
    - group.my_room
    - group.my_desk
    - group.my_bed
    - group.my_door
    - group.my_car
    - group.my_gadget
    - group.speaker
    - group.livingroom

weather:
  name: Outside Weather
  entities:
    - sensor.weather_temperature
    - sensor.weather_humidity_with_icon
    - sun.sun
    - sensor.weather_symbol

sensor:
  name: My Room Condition
  entities:
    - sensor.room_temperature
    - sensor.room_humidity
    - sensor.room_pm25
    - sensor.room_illuminance
    - fan.mi_air_purifier
    - fan.mi_humidifier
    - fan.mi_standing_fan
    - switch.samsung_air_conditioner

main_door:
  name: Main Door
  entities:
    - binary_sensor.main_door_status
    - binary_sensor.passage_motion

my_room:
  name: My Room
  entities:
    - binary_sensor.room_door_status
    - binary_sensor.room_door_motion
    - binary_sensor.window_sensor
    - cover.myroom_curtain
    - cover.mywindow_curtain
    - binary_sensor.security_manual_stop
    - light.gateway_light

my_desk:
  name: My Desk
  entities:
    - binary_sensor.yunhan_desktop
    - binary_sensor.desktop_switch
    - light.desk_lamp

my_bed:
  name: My Bed
  entities:
    - binary_sensor.room_bed_motion
    - binary_sensor.room_bed_sleep
    - light.sleep_lamp

people:
  name: People
  entities:
    - binary_sensor.yunhan_android
    - binary_sensor.minjun_android
    - binary_sensor.hyunjun_android
    - binary_sensor.mom_iphone
    - binary_sensor.grandma_android

my_gadget:
  name: My Gadget
  entities:
    - sensor.mi_scale
    - binary_sensor.gear_s3
    - binary_sensor.gear_fit2_pro
    - binary_sensor.airpods

my_car:
  name: My Car
  entities:
    - binary_sensor.bmw

speaker:
  name: Speaker
  entities:
    - sensor.sonos_playlist
    - binary_sensor.sonos_manual_stop
    - media_player.playroom
    - media_player.googlehome

livingroom:
  name: Livingroom
  entities:
    - sensor.livingroom_temperature
    - sensor.livingroom_humidity
    - sensor.livingroom_pm25
    - fan.mi_air_purifier_livingroom
    - switch.livingroom_tv
    - vacuum.mi_robot_vacuum
