default_view:
  name: Home
  view: yes
  icon: mdi:home
  entities:
    - group.weather
    - group.sensor
    - group.people
    - group.system
    - group.light
    - group.fan
    - group.airconditioner
    - group.vacuum
    - group.speaker

weather:
  name: Weather
  entities:
    - sensor.weather_temperature
    - sensor.weather_humidity_with_icon
    - sensor.weather_symbol
    - sun.sun

sensor:
  name: Sensor
  entities:
    - sensor.room_temperature
    - sensor.room_humidity
    - sensor.room_illuminance
    - binary_sensor.main_door_status
    - binary_sensor.main_door_motion
    - binary_sensor.room_door_motion
    - binary_sensor.room_bed_motion
    - binary_sensor.room_bed_sleep

people:
  name: People
  entities:
    - binary_sensor.yunhan_android
    - binary_sensor.minjun_android
    - binary_sensor.hyunjun_android
    - binary_sensor.jiyeon_iphone

system:
  name: System
  entities:
    - binary_sensor.yunhan_desktop

light:
  name: Lights
  entities:
    - light.desk_lamp
    - light.sleep_lamp

speaker:
  name: Speaker
  entities:
    - media_player.playroom

fan:
  name: Air
  entities:
    - switch.mi_air_purifier
    - switch.mi_standing_fan
    - switch.samsung_air_conditioner

#airconditioner:
#  name: Air Conditioner
#  entities:
#    - script.script_turn_on_my_room_ac
#    - script.script_turn_off_my_room_ac

vacuum:
  name: Vacuum
  entities:
    - vacuum.mi_robot_vacuum
