- platform: yr
  name: Weather
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog

- platform: mqtt
  state_topic: smartthings/Yunhan's GS8/presence
  name: Yunhan's GS8

#- platform: mqtt
#  state_topic: smartthings/Daddy's Room Bed Sensor/temperature
#  name: Room Temperature
#  unit_of_measurement: "°C"

#- platform: mqtt
#  state_topic: smartthings/Daddy's Room Bed Sensor/humidity
#  name: Room Humidity
#  unit_of_measurement: "%"
- platform: template
  sensors:
    room_temperature:
      friendly_name: Room Temperature
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ '%.1f'|format(states.fan.mi_air_purifier.attributes.temperature) }}"

    room_humidity:
      friendly_name: Room Humidity
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ states.fan.mi_air_purifier.attributes.humidity }}"

    yunhan_desktop:
      friendly_name: Yunhan's Desktop PC
      icon_template: "mdi:monitor"
      value_template: "{% if is_state('device_tracker.spbear_desktop', 'home') %}on{% else %}off{% endif %}"

    yunhan_android:
      friendly_name: Yunhan's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{% if states.sensor.yunhans_gs8.state == 'present' %}home{% else %}away{% endif %}"

    minjun_android:
      friendly_name: Minjun's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{% if states.device_tracker.minjun_android.state == 'home' %}home{% else %}away{% endif %}"

    hyunjun_android:
      friendly_name: Hyunjun's Android
      icon_template: "mdi:cellphone-android"
      value_template: "{% if states.device_tracker.hyunjun_android.state == 'home' %}home{% else %}away{% endif %}"

    jiyeon_iphone:
      friendly_name: Jiyeon's iPhone
      icon_template: "mdi:cellphone-iphone"
      value_template: "{% if states.device_tracker.jiyeon_iphone.state == 'home' %}home{% else %}away{% endif %}"

    weather_humidity_with_icon:
      friendly_name: Weather Humidity
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ states.sensor.weather_humidity.state }}"

- platform: mqtt
  state_topic: smartthings/Daddy's Room Bed Sensor/illuminance
  unit_of_measurement: "lux"
  device_class: illuminance
  name: Room Illuminance

- platform: mqtt
  state_topic: smartthings/Main Door/contact
  name: Main Door Status

- platform: mqtt
  state_topic: smartthings/Main Door/acceleration
  name: Main Door Motion

- platform: mqtt
  state_topic: smartthings/Daddy's Room Door Sensor/motion
  name: Room Door Motion

- platform: mqtt
  state_topic: smartthings/Daddy's Room Bed Sensor/motion
  name: Room Bed Motion

- platform: mqtt
  state_topic: smartthings/Nokia Sleep/switch
  name: Room Bed Sleep
  icon: mdi:hotel
  value_template: "{% if states.sensor.room_bed_sleep == 'on' %}on the bed{% else %}away{% endif %}"
