- platform: yr
  name: Weather
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog

- platform: mqtt
  state_topic: smartthings/Yunhan's GS8/presence
  name: Yunhan's GS8
  force_update: True

- platform: template
  sensors:
    room_temperature:
      friendly_name: Room Temperature
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ '%.1f'|format(states.fan.mi_air_purifier.attributes.temperature) }}"

    room_humidity:
      friendly_name: Room Humidity
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ states.fan.mi_air_purifier.attributes.humidity }}"

    room_illuminance:
      friendly_name: Room Illuminance
      unit_of_measurement: "lux"
      device_class: illuminance
      value_template: "{{ '%d' | format((states.sensor.gateway_illumination.state | float) * 0.2152782) }}"

    room_pm25:
      friendly_name: Room PM2.5
      unit_of_measurement: "㎍/m³"
      value_template: "{{ states.fan.mi_air_purifier.attributes.aqi | int }}"

    weather_humidity_with_icon:
      friendly_name: Weather Humidity
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ states.sensor.weather_humidity.state }}"

    livingroom_temperature:
      friendly_name: Living Room Temperature
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ '%.1f'|format(states.fan.mi_air_purifier_livingroom.attributes.temperature) }}"

    livingroom_humidity:
      friendly_name: Living Room Humidity
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ states.fan.mi_air_purifier_livingroom.attributes.humidity }}"

    livingroom_pm25:
      friendly_name: Living Room PM2.5
      unit_of_measurement: "㎍/m³"
      value_template: "{{ states.fan.mi_air_purifier_livingroom.attributes.aqi | int }}"


- platform: mqtt
  state_topic: sonos/playlist
  name: Sonos Playlist

- platform: mqtt
  name: "Mi Scale"
  state_topic: "bt-gateway/miscale/weight/kg"
  value_template: "{{ '%.1f'|format(value | float) }}"
  unit_of_measurement: "kg"
