#- platform: yr
#  name: Weather
#  monitored_conditions:
#    - symbol
#    - temperature
#    - humidity
#    - fog

- platform: rest
  name: Awair 2nd Edition
  json_attributes:
    - temp
    - humid
    - co2
    - voc
    - pm25
    - score
  resource: !secret awair_url
  value_template: '{{value_json.score}}'

- platform: template
  sensors:
    awair_temperature:
      friendly_name: My Room Temperature
      value_template: "{{ state_attr('sensor.awair_2nd_edition', 'temp') | round(1) }}"
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
    awair_humidity:
      friendly_name: My Room Humidity
      value_template: "{{ state_attr('sensor.awair_2nd_edition', 'humid') | round(1) }}"
      icon_template: mdi:water-percent
      unit_of_measurement: '%'
    awair_score:
      friendly_name: My Room Air Score
      value_template: "{{ state_attr('sensor.awair_2nd_edition', 'score') | round(0) }}"
      icon_template: mdi:percent
      unit_of_measurement: '%'
    awair_voc:
      friendly_name: My Room VOC
      value_template: "{{ state_attr('sensor.awair_2nd_edition', 'voc') | round(0) }}"
      icon_template: mdi:chemical-weapon
      unit_of_measurement: 'ppb'
    awair_co2:
      friendly_name: My Room CO2
      value_template: "{{ state_attr('sensor.awair_2nd_edition', 'co2') | round(0) }}"
      icon_template: mdi:periodic-table-co2
      unit_of_measurement: 'ppm'
    awair_pm2_5:
      friendly_name: My Room PM2.5
      value_template: "{{ state_attr('sensor.awair_2nd_edition', 'pm25') | round(1) }}"
      icon_template: mdi:cloud
      unit_of_measurement: 'µg/m³'


- platform: template
  sensors:
    room_temperature:
      friendly_name: Room Temperature
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ '%.1f'|format(states.fan.mi_air_purifier.attributes.temperature) }}"

    washing_machine_power:
      friendly_name: Washing Machine Power
      unit_of_measurement: "W"
      device_class: power
      value_template: "{{ '%.1f'|format(float(states.switch.washing_machine.attributes.current_power_w)) }}"

    washing_machine_energy:
      friendly_name: Washing Machine Energy
      unit_of_measurement: "kWh"
      device_class: power
      value_template: "{{ '%.1f'|format(float(states.switch.washing_machine.attributes.today_energy_kwh)) }}"

    livingroom_tv_power:
      friendly_name: Livingroom TV Power
      unit_of_measurement: "W"
      device_class: power
      value_template: "{{ '%.1f'|format(float(states.switch.livingroom_tv_plug.attributes.current_power_w)) }}"

    livingroom_tv_energy:
      friendly_name: Livingroom TV Energy
      unit_of_measurement: "kWh"
      device_class: power
      value_template: "{{ '%.1f'|format(float(states.switch.livingroom_tv_plug.attributes.today_energy_kwh)) }}"

    livingroom_airconditioner_power:
      friendly_name: Livingroom Airconditioner Power
      unit_of_measurement: "W"
      device_class: power
      value_template: "{{ '%.1f'|format(float(states.switch.livingroom_airconditioner_plug.attributes.current_power_w)) }}"

    livingroom_airconditioner_energy:
      friendly_name: Livingroom Airconditioner Energy
      unit_of_measurement: "kWh"
      device_class: power
      value_template: "{{ '%.1f'|format(float(states.switch.livingroom_airconditioner_plug.attributes.today_energy_kwh)) }}"

    room_humidity:
      friendly_name: Room Humidity
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ states.fan.mi_air_purifier.attributes.humidity }}"

    room_illuminance:
      friendly_name: Room Illuminance
      unit_of_measurement: "lux"
      device_class: illuminance
      value_template: "{{ '%.1f' | format((states.sensor.light_sensor.state | float)) }}"

    room_pm25:
      friendly_name: Room PM2.5
      unit_of_measurement: "㎍/m³"
      value_template: "{{ states.fan.mi_air_purifier.attributes.aqi | int }}"

    livingroom_temperature:
      friendly_name: Living Room Temperature
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ '%.1f'|format(states.fan.mi_air_purifier_livingroom.attributes.temperature) }}"

    livingroom_humidity:
      friendly_name: Living Room Humidity
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ states.fan.mi_air_purifier_livingroom.attributes.humidity }}"

    livingroom_pm25:
      friendly_name: Living Room PM2.5
      unit_of_measurement: "㎍/m³"
      value_template: "{{ states.fan.mi_air_purifier_livingroom.attributes.aqi | int }}"

    dehumidifier_ip:
      value_template: !secret xiaomi_dehumidifier_ip

    dehumidifier_token:
      value_template: !secret dehumidifier_token


- platform: mqtt
  name: "Mi Scale"
  state_topic: "bt-gateway/miscale/weight/kg"
  value_template: "{{ '%.1f'|format(value | float) }}"
  unit_of_measurement: "kg"

- platform: mqtt
  name: "Light Sensor"
  state_topic: "smartthings/Light Sensor/illuminance"
  value_template: "{{ '%.1f'|format(value | float) }}"
  unit_of_measurement: "lux"

- platform: mqtt
  name: "Weather Sensor Temperature"
  state_topic: "smartthings/Weather Sensor/temperature"
  value_template: "{{ '%.1f'|format(value | float) }}"
  unit_of_measurement: "°C"

- platform: mqtt
  name: "Weather Sensor Humidity"
  state_topic: "smartthings/Weather Sensor/humidity"
  value_template: "{{ '%.1f'|format(value | float) }}"
  unit_of_measurement: "%"

- platform: miflora
  name: 'Bengal Rubber Tree'
  mac: !secret miflora_bengal_rubber_tree_mac
  monitored_conditions:
    - moisture
    - light
    - battery
    - temperature
    - conductivity

# MiFlora Setting
- platform: mqtt
  name: "Goldcrest Wilma Mositure"
  state_topic: "miflora/status/GoldcrestWilma/moisture"
  value_template: "{{ value_json.val }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: "Pilea Peperomidoides Mositure"
  state_topic: "miflora/status/PileaPeperomidoides/moisture"
  value_template: "{{ value_json.val }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: "TravelersTree Mositure"
  state_topic: "miflora/status/TravelersTree/moisture"
  value_template: "{{ value_json.val }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: "Areca Palm Mositure"
  state_topic: "miflora/status/ArecaPalm/moisture"
  value_template: "{{ value_json.val }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: "Monstera Mositure"
  state_topic: "miflora/status/Monstera/moisture"
  value_template: "{{ value_json.val }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: "Jerusalem Cherry Mositure"
  state_topic: "miflora/status/JerusalemCherry/moisture"
  value_template: "{{ value_json.val }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: "Poinsettia Mositure"
  state_topic: "miflora/status/Poinsettia/moisture"
  value_template: "{{ value_json.val }}"
  unit_of_measurement: "%"


# sensors.yaml
# 한국환경공단 검단 관측소 실시간 정보
- platform: rest
  name: air_quality_time
  scan_interval: 900. # 900초(15분)마다 반복, 매 정시에 정보가 갱신되지만 지연이 있는 경우가 있으므로
  json_attributes:
    - list
  value_template: '{{ value_json["list"][0]["dataTime"] }}'
  resource: !secret air_quality_api

- platform: template
  sensors:
    air_quality_khaivalue:    #통합대기환경수치
      value_template: '{{ states.sensor.air_quality_time.attributes["list"][0]["khaiValue"] }}'
    air_quality_pm25value:    #초미세먼지 농도
      value_template: '{{ states.sensor.air_quality_time.attributes.list[0]["pm25Value"] }}'
      unit_of_measurement: "㎍/m³"
      entity_id: sensor.air_quality_time
    air_quality_pm10value:    #미세먼지 농도
      value_template: '{{ states.sensor.air_quality_time.attributes.list[0]["pm10Value"] }}'
      unit_of_measurement: "㎍/m³"
    air_quality_o3value:    #오존 농도
      value_template: '{{ states.sensor.air_quality_time.attributes.list[0]["o3Value"] }}'
      unit_of_measurement: "ppm"
    air_quality_covalue:    #일산화탄소 농도
      value_template: '{{ states.sensor.air_quality_time.attributes.list[0]["coValue"] }}'
      unit_of_measurement: "ppm"
    air_quality_no2value:    #이산화질소 농도
      value_template: '{{ states.sensor.air_quality_time.attributes.list[0]["no2Value"] }}'
      unit_of_measurement: "ppm"
    air_quality_so2value:    #아황산화탄소 농도
      value_template: '{{ states.sensor.air_quality_time.attributes.list[0]["so2Value"] }}'
      unit_of_measurement: "ppm"
    air_quality_khaigrade:    #통합대기환경지수
      value_template: '{% if states.sensor.air_quality_time.attributes.list[0]["khaiGrade"] == "1" %}Good
                       {% elif states.sensor.air_quality_time.attributes.list[0]["khaiGrade"] == "2" %}Normal
                       {% elif states.sensor.air_quality_time.attributes.list[0]["khaiGrade"] == "3" %}Bad
                       {% elif states.sensor.air_quality_time.attributes.list[0]["khaiGrade"] == "4" %}Very Bad
                       {% else %}N/A
                       {% endif %}'
    air_quality_pm25grade:    #초미세먼지 등급
      value_template: '{% if states.sensor.air_quality_time.attributes.list[0]["pm25Grade1h"]  == "1" %}Good
                       {% elif states.sensor.air_quality_time.attributes.list[0]["pm25Grade1h"] == "2" %}Normal
                       {% elif states.sensor.air_quality_time.attributes.list[0]["pm25Grade1h"] == "3" %}Bad
                       {% elif states.sensor.air_quality_time.attributes.list[0]["pm25Grade1h"] == "4" %}Very Bad
                       {% else %}N/A
                       {% endif %}'
    air_quality_pm10grade:    #미세먼지 등급
      value_template: '{% if states.sensor.air_quality_time.attributes.list[0]["pm10Grade1h"] == "1" %}Good
                       {% elif states.sensor.air_quality_time.attributes.list[0]["pm10Grade1h"] == "2" %}Normal
                       {% elif states.sensor.air_quality_time.attributes.list[0]["pm10Grade1h"] == "3" %}Bad
                       {% elif states.sensor.air_quality_time.attributes.list[0]["pm10Grade1h"] == "4" %}Very Bad
                       {% else %}N/A
                       {% endif %}'
    air_quality_o3grade:  #오존 지수
      value_template: '{% if states.sensor.air_quality_time.attributes.list[0]["o3Grade"] == "1" %}Good
                       {% elif states.sensor.air_quality_time.attributes.list[0]["o3Grade"] == "2" %}Normal
                       {% elif states.sensor.air_quality_time.attributes.list[0]["o3Grade"] == "3" %}Bad
                       {% elif states.sensor.air_quality_time.attributes.list[0]["o3Grade"] == "4" %}Very Bad
                       {% else %}N/A
                       {% endif %}'
    air_quality_cograde:  #일산화탄소 지수
      value_template: '{% if states.sensor.air_quality_time.attributes.list[0]["coGrade"] == "1" %}Good
                       {% elif states.sensor.air_quality_time.attributes.list[0]["coGrade"] == "2" %}Normal
                       {% elif states.sensor.air_quality_time.attributes.list[0]["coGrade"] == "3" %}Bad
                       {% elif states.sensor.air_quality_time.attributes.list[0]["coGrade"] == "4" %}Very Bad
                       {% else %}N/A
                       {% endif %}'
