- platform: mqtt
  name: "Samsung Air Conditioner"
  state_topic: "smartthings/Samsung Air Conditioner/switch"
  command_topic: "smartthings/Samsung Air Conditioner/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:air-conditioner
  optimistic: false
  retain: true

- platform: template
  switches:
    screen_projector:
      friendly_name: "Screen Projector"
      value_template: "{{ is_state('binary_sensor.screen_projector', 'on')}}"
      turn_on:
        service: script.script_power_gs1
      turn_off:
        service: script.script_power_gs1

- platform: mqtt
  name: "Monitor"
  state_topic: "smartthings/Monitor/switch"
  command_topic: "smartthings/Monitor/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  optimistic: false
  retain: true

- platform: mqtt
  name: "MiBox"
  state_topic: "smartthings/MiBox/switch"
  command_topic: "smartthings/MiBox/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  optimistic: false
  retain: true
#  switches:
#    mibox:
#      friendly_name: "MIBOX"
#      value_template: "{{ is_state('media_player.mibox', 'playing')}}"
#      turn_on:
#        service: androidtv.adb_command
#        data:
#            entity_id: media_player.mibox
#            command: "POWER"
#      turn_off:
#        service: androidtv.adb_command
#        data:
#            entity_id: media_player.mibox
#            command: "HOME"

- platform: template
  switches:
    roll_screen:
      friendly_name: "Roll Screen"
      value_template: "{{ not is_state('cover.roll_screen', 'open')}}"
      turn_on:
        service: cover.close_cover
        data:
            entity_id: cover.roll_screen
      turn_off:
        service: cover.open_cover
        data:
            entity_id: cover.roll_screen

- platform: template
  switches:
    livingroom_tv:
      friendly_name: "Living Room TV"
      value_template: "{{ is_state('media_player.livingroom_tv', 'on')}}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.livingroom_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.livingroom_tv

- platform: mqtt
  name: "Mi Dehumidifier"
  state_topic: "switch/mi_dehumidifier"
  command_topic: "switch/mi_dehumidifier"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:fan
  optimistic: false
  retain: true

- platform: mqtt
  name: "Music Auto Play"
  state_topic: "switch/music_auto_play"
  command_topic: "switch/music_auto_play"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:music
  optimistic: false
  retain: true

- platform: mqtt
  name: "Fan Direction To Desk"
  state_topic: switch/fan_direction_to_desk
  command_topic: "switch/fan_direction_to_desk"
  payload_on: 'on'
  payload_off: 'off'
  state_on: "on"
  state_off: "off"
  icon: mdi:fan
  optimistic: false
  retain: true

- platform: mqtt
  name: "Security Mode"
  state_topic: "switch/security_mode"
  command_topic: "switch/security_mode"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:security
  optimistic: false
  retain: true

- platform: mqtt
  name: "Curtain Auto Control"
  state_topic: "switch/curtain_auto_control"
  command_topic: "switch/curtain_auto_control"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:animation
  optimistic: false
  retain: true

- platform: mqtt
  name: "Restroom Fan"
  state_topic: "smartthings/Restroom Fan/switch"
  command_topic: "smartthings/Restroom Fan/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  optimistic: false
  retain: true

- platform: mqtt
  name: "Restroom Light"
  state_topic: "smartthings/Restroom Light/switch"
  command_topic: "smartthings/Restroom Light/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  optimistic: false
  retain: true

- platform: mqtt
  name: "Restroom Sub Light"
  state_topic: "smartthings/Restroom Sub Light/switch"
  command_topic: "smartthings/Restroom Sub Light/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  optimistic: false
  retain: true

- platform: mqtt
  name: "My Room Light"
  state_topic: "smartthings/My Room Light/switch"
  command_topic: "smartthings/My Room Light/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  optimistic: false
  retain: true
