- platform: mqtt
  name: "Samsung Air Conditioner"
  state_topic: "smartthings/Samsung Air Conditioner/switch"
  command_topic: "smartthings/Samsung Air Conditioner/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:air-conditioner
  optimistic: false
  retain: true

- platform: template
  switches:
    livingroom_tv:
      friendly_name: "Living Room TV"
      value_template: "{{ is_state('media_player.livingroom_tv', 'on')}}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.livingroom_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.livingroom_tv

- platform: mqtt
  name: "Music Auto Play"
  state_topic: "switch/music_auto_play"
  command_topic: "switch/music_auto_play"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:music
  optimistic: false
  retain: true

- platform: mqtt
  name: "Security Mode"
  state_topic: "switch/security_mode"
  command_topic: "switch/security_mode"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:security
  optimistic: false
  retain: true
