- platform: mqtt
  name: "Samsung Air Conditioner"
  state_topic: "smartthings/Samsung Air Conditioner/switch"
  command_topic: "smartthings/Samsung Air Conditioner/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:air-conditioner
  optimistic: false
  retain: true

- platform: template
  switches:
    livingroom_tv:
      value_template: "{{ is_state('media_player.livingroom_tv', 'on')}}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.livingroom_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.livingroom_tv
