- platform: switchbot
  name: "Passage Light Switchbot"
  mac: !secret passage_light_switchbot_mac

- platform: mqtt
  name: "Passage Light"
  state_topic: "smartthings/Passage Light/switch"
  command_topic: "smartthings/Passage Light/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:lightbulb
  optimistic: false
  retain: true

- platform: switchbot
  name: "Heating Control Switchbot"
  mac: !secret heating_control_switchbot_mac

- platform: mqtt
  name: "Heating Control"
  state_topic: "smartthings/Heating Control/switch"
  command_topic: "smartthings/Heating Control/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:fire
  optimistic: false
  retain: true

- platform: mqtt
  name: "Samsung Air Conditioner"
  state_topic: "smartthings/Samsung Air Conditioner/switch"
  command_topic: "smartthings/Samsung Air Conditioner/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:air-conditioner
  optimistic: false
  retain: true

- platform: template
  switches:
    screen_projector:
      friendly_name: "Screen Projector"
      value_template: "{{ is_state('binary_sensor.screen_projector', 'on')}}"
      turn_on:
        service: script.script_power_gs1
      turn_off:
        service: script.script_power_gs1

- platform: mqtt
  name: "MiBox"
  state_topic: "smartthings/MiBox/switch"
  command_topic: "smartthings/MiBox/switch"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  optimistic: false
  retain: true
#  switches:
#    mibox:
#      friendly_name: "MIBOX"
#      value_template: "{{ is_state('media_player.mibox', 'playing')}}"
#      turn_on:
#        service: androidtv.adb_command
#        data:
#            entity_id: media_player.mibox
#            command: "POWER"
#      turn_off:
#        service: androidtv.adb_command
#        data:
#            entity_id: media_player.mibox
#            command: "HOME"

- platform: template
  switches:
    roll_screen:
      friendly_name: "Roll Screen"
      value_template: "{{ not is_state('cover.roll_screen', 'open')}}"
      turn_on:
        service: cover.close_cover
        data:
            entity_id: cover.roll_screen
      turn_off:
        service: cover.open_cover
        data:
            entity_id: cover.roll_screen

    livingroom_tv_real:
      friendly_name: "Livingroom TV"
      value_template: "{{ float(states.switch.livingroom_tv.attributes.power) > 2.0 }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.livingroom_tv
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.livingroom_tv

- platform: mqtt
  name: "Mi Dehumidifier"
  state_topic: "switch/mi_dehumidifier"
  command_topic: "switch/mi_dehumidifier"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:fan
  optimistic: false
  retain: true

- platform: mqtt
  name: "Music Auto Play"
  state_topic: "switch/music_auto_play"
  command_topic: "switch/music_auto_play"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:music
  optimistic: false
  retain: true

- platform: mqtt
  name: "Fan Direction To Desk"
  state_topic: switch/fan_direction_to_desk
  command_topic: "switch/fan_direction_to_desk"
  payload_on: 'on'
  payload_off: 'off'
  state_on: "on"
  state_off: "off"
  icon: mdi:fan
  optimistic: false
  retain: true

- platform: mqtt
  name: "Security Mode"
  state_topic: "switch/security_mode"
  command_topic: "switch/security_mode"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:security
  optimistic: false
  retain: true

- platform: mqtt
  name: "Curtain Auto Control"
  state_topic: "switch/curtain_auto_control"
  command_topic: "switch/curtain_auto_control"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  icon: mdi:animation
  optimistic: false
  retain: true
